---
title: "class07"
author: "Aashna Bhargava"
date: "2026-09-16"
output:
  html_document:
    toc: TRUE
    toc_float: TRUE #wanna have toc on the left side
    number_sections: TRUE #gonna call them section 1 and 2
    code_folding: show #shows or hides code
    code_download: TRUE # allows you to download the document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##demo

```{r demo}
con = DBI::dbConnect(RSQLite::SQLite(), "../data/scout.db")
postings = DBI::dbReadTable(con, "scout_postings") |> tibble::as_tibble()
DBI::dbDisconnect(con)


jobs = postings |>
  dplyr::select(company, title, location_state, remote, category, posted_at, last_seen_at) |>
  dplyr::mutate(dplyr::across(dplyr::ends_with("_at"), as.Date),
                days_open = as.numeric(last_seen_at - posted_at))

#For Q1, to answer it, we need the following:
#number of jobs  per category
#- fraction of those jobs that are remote friendly 

jobs |> 
  dplyr::group_by(category) |> 
  dplyr::summarise(
    postings = dplyr::n(), #counting the number of rows per category 
    remote_share = mean(remote) |>  round(3)
  )

#Q2: Among the full time jobs, which states have the highest remote share?
jobs |> 
  dplyr::filter(category == 'fulltime') |> 
  dplyr::group_by(location_state) |> 
   dplyr::summarise(
    postings = dplyr::n(), #counting the number of rows per category 
    remote_share = mean(remote) |>  round(3) 
  )  |> 
  dplyr::filter(postings >= 50) |> #up to you to determine min threshold
  dplyr::arrange(dplyr::desc(remote_share)) |> 
  head(3)
      
      
```

```{r}
##In class practice Qs

con = DBI::dbConnect(RSQLite::SQLite(), "../data/midwest_airbnb.db")
listings = DBI::dbReadTable(con, "listings") |>
  tibble::as_tibble()
DBI::dbDisconnect(con)
dplyr::glimpse(listings)

#Q1: Approach (a) would be to simply count the repitions within the city column (see how many times chicago, columbus etc... are said)
table(listings$city)

#alternativley, group by > summarize (n()) -- returns a data frame in (a) we returned a named vector 

listings |>
  dplyr::group_by(city) |> 
  dplyr::summarise(
    city_count = dplyr::n()
    
  ) -> practice_q1

# Q2: for entire homes (room_types == "entire home/ apt") that sleep four or more, what is the medican price in each city?

listings |> 
  dplyr::filter(
    room_type == "Entire home/apt" & accommodates >= 4
  ) |> 
  dplyr::group_by(city) |> 
  dplyr::summarise(
    median_price = median(price)
  )

#Q3: Add price_per_person = price / accommodates. Which three listings are cheapest per person? Believe them? THIS IS PER LISTING and we need to create a new col

listings |> 
  dplyr::mutate(
    price_per_person = price / accommodates#LHS = new col name; RHS is the math use to create the new col [this s done row by row]
  ) |> 
  dplyr::arrange(price_per_person) |> 
  #don't NEED to fo this step, doing it so we can look at the output in a more compact way
  dplyr::select(city,name,price,accommodates,price_per_person) |> 
  head(3)

#Q5: Which five host_names have the most listings?
listings |> 
  dplyr::count(host_name, host_id, sort = T) #shortcut for group_by and then n()


```

